version: "3.8"
services:
  mysql:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "devops"
    ports:
    - "3307:3306"
    volumes:
    - my_data:/var/lib/mysql
    networks:
    - flask-app
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

 
  flask:
    build:
      context: .
    container_name: flask-container
    ports:
    - "5001:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DB: devops 
    networks:
    - flask-app
    depends_on:
    - mysql
    healthcheck:
      test: ["CMD-SHELL","curl -f http://localhost:5001/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s 

volumes:
  my_data:

networks:
  flask-app:
